apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-2hw5
  namespace: e2e-demos-vtwf-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/test-images-protected@sha256:cf7007beb2a12cf016645996f11c1f018e84ae24dbee586847b5c439b8b84bf6
        name: my-nodejs
        resources: {}
status: {}
